#!/usr/bin/env python3
"""Generate docs/api/endpoints.md from openapi.json.

The endpoint inventory is the single highest-drift content in the API domain
(hand-kept tables of every route). It is mechanically derivable from the OpenAPI
contract, so it is generated here rather than maintained by hand, and is excluded
from the <300-line spec rule as a generated artifact (cf. apps/web .../schema.gen.ts).

Committed, like schema.gen.ts: re-run `just docs gen-endpoints` after an API
change and commit the result; the docs build re-runs it so the site is never stale.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "openapi.json"
OUT = ROOT / "docs" / "api" / "endpoints.md"

METHOD_ORDER = ["get", "post", "put", "patch", "delete", "head", "options", "trace"]


def main() -> None:
    spec = json.loads(OPENAPI.read_text())
    tag_order = [t["name"] for t in spec.get("tags", [])]
    tag_summaries = {t["name"]: t.get("description", "") for t in spec.get("tags", [])}

    # Bucket operations by their first tag (untagged → "other").
    by_tag: dict[str, list[tuple[str, str, str, str]]] = {}
    for path, item in spec.get("paths", {}).items():
        for method in METHOD_ORDER:
            op = item.get(method)
            if not op:
                continue
            tag = (op.get("tags") or ["other"])[0]
            summary = op.get("summary", "") or op.get("description", "").split("\n")[0]
            op_id = op.get("operationId", "")
            by_tag.setdefault(tag, []).append((method.upper(), path, summary, op_id))

    ordered_tags = [t for t in tag_order if t in by_tag]
    ordered_tags += sorted(t for t in by_tag if t not in tag_order)

    out: list[str] = []
    out.append("<!-- GENERATED by tools/docs/gen_endpoints.py from openapi.json — do not edit by hand. -->")
    out.append("")
    out.append("# API endpoint inventory")
    out.append("")
    out.append(
        "Generated from `openapi.json`, the source of truth for the `/v1` HTTP "
        "surface (see [API contract](L1.md)). Every operation, grouped by tag."
    )
    out.append("")
    for tag in ordered_tags:
        out.append(f"## {tag}")
        desc = tag_summaries.get(tag, "")
        if desc:
            out.append("")
            out.append(desc)
        out.append("")
        out.append("| Method | Path | Summary | Operation |")
        out.append("| --- | --- | --- | --- |")
        for method, path, summary, op_id in sorted(by_tag[tag], key=lambda r: (r[1], r[0])):
            op_cell = f"`{op_id}`" if op_id else ""
            out.append(f"| `{method}` | `{path}` | {summary} | {op_cell} |")
        out.append("")

    OUT.write_text("\n".join(out).rstrip() + "\n")
    n_ops = sum(len(v) for v in by_tag.values())
    print(f"wrote {OUT.relative_to(ROOT)} — {n_ops} operations across {len(ordered_tags)} tags")


if __name__ == "__main__":
    main()
