# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: v0.2.0
_src_path: git@github.com:theoryzhenkov/repo_template.base_mkdocs.git
project_description: ''
project_name: posthaste
