import { Circle, Paperclip, Star } from 'lucide-react'
import type { CSSProperties } from 'react'
import type { MailboxView, MessagePreview } from './types'

// Auto-generated by apps/site/tools/gen-collision-keyframes.mjs (v3)
// Snowplow model: all letters scatter rightward; cascade resolves overlaps.
// ax/ay/ar = position at 40 % of scatter animation (arc peak)
// px/py/pr = final resting position (100 %)
// prettier-ignore
const LETTER_PHYSICS = [
  { delay: 354, ax:  106, ay:  -18, ar:  -19.5, px:  163, py:  -27, pr:  -29.9 }, // A
  { delay: 387, ax:   95, ay:   10, ar:   14.6, px:  145, py:   16, pr:   22.4 }, // l
  { delay: 405, ax:  104, ay:  -26, ar:  -25.6, px:  159, py:  -40, pr:  -39.2 }, // l
  { delay: 424, ax:  114, ay:  -18, ar:  -19.1, px:  175, py:  -28, pr:  -29.3 }, // (space)
  { delay: 455, ax:  120, ay:  -26, ar:  -25.8, px:  184, py:  -41, pr:  -39.5 }, // q
  { delay: 497, ax:  120, ay:  -10, ar:  -10.5, px:  184, py:  -15, pr:  -16.2 }, // u
  { delay: 526, ax:  112, ay:    8, ar:   17.9, px:  172, py:   12, pr:   27.5 }, // i
  { delay: 553, ax:   93, ay:   11, ar:   18.6, px:  143, py:   17, pr:   28.5 }, // e
  { delay: 585, ax:  102, ay:  -22, ar:  -19.8, px:  157, py:  -33, pr:  -30.3 }, // t
  { delay: 606, ax:  107, ay:  -22, ar:    -20, px:  165, py:  -34, pr:  -30.7 }, // !
  { delay: 623, ax:  101, ay:   20, ar:   23.8, px:  155, py:   31, pr:   36.5 }, // (space)
  { delay: 657, ax:  106, ay:   21, ar:   22.3, px:  163, py:   32, pr:   34.1 }, // Z
  { delay: 700, ax:  113, ay:   -3, ar:  -13.1, px:  173, py:   -4, pr:    -20 }, // e
  { delay: 733, ax:  109, ay:   -2, ar:   -7.6, px:  167, py:   -4, pr:  -11.6 }, // r
  { delay: 767, ax:   84, ay:   14, ar:   14.4, px:  129, py:   22, pr:     22 }, // o
  { delay: 798, ax:  104, ay:   24, ar:     21, px:  160, py:   36, pr:   32.2 }, // (space)
  { delay: 815, ax:   82, ay:  -16, ar:  -20.4, px:  126, py:  -24, pr:  -31.2 }, // i
  { delay: 844, ax:  104, ay:   -6, ar:    -16, px:  159, py:  -10, pr:  -24.5 }, // n
  { delay: 886, ax:   94, ay:   27, ar:   22.2, px:  143, py:   41, pr:   34.1 }, // b
  { delay: 928, ax:   75, ay:   -9, ar:  -13.4, px:  114, py:  -14, pr:  -20.6 }, // o
  { delay: 969, ax:   82, ay:   23, ar:   19.9, px:  126, py:   36, pr:   30.5 }, // x
] as const

export function MessageListPreview({
  messages,
  selectedMessageId,
  selectedMailbox,
  horseClicks,
  isHorseLaunching,
  isSecretThemeUnlocked,
  onSecretHorseClick,
  onSelectMessage,
}: {
  messages: MessagePreview[]
  selectedMessageId: string | null
  selectedMailbox: MailboxView
  horseClicks: number
  isHorseLaunching: boolean
  isSecretThemeUnlocked: boolean
  onSecretHorseClick: () => void
  onSelectMessage: (messageId: string) => void
}) {
  const isZeroInbox = selectedMailbox === 'inbox' && messages.length === 0

  const scatterActive = isZeroInbox && !isSecretThemeUnlocked

  return (
    <section className="mock-list" aria-label="Conversation list preview">
      <div className="list-heading">
        <span aria-label="Unread">
          <Circle aria-hidden="true" />
        </span>
        <span aria-label="Flagged">
          <Star aria-hidden="true" />
        </span>
        <span aria-label="Attachment">
          <Paperclip aria-hidden="true" />
        </span>
        <span>Subject</span>
        <span>From</span>
        <span>Date received</span>
        <span>Account</span>
      </div>
      {isZeroInbox ? (
        <div className="zero-inbox-stage">
          <p className="zero-inbox-letters" aria-label="All quiet! Zero inbox">
            {'All quiet! Zero inbox'.split('').map((letter, index) => {
              const p = LETTER_PHYSICS[index]
              return (
                <span
                  key={`${letter}-${index}`}
                  style={
                    scatterActive
                      ? ({
                          animationDelay: `${p.delay}ms`,
                          '--ax': `${p.ax}px`,
                          '--ay': `${p.ay}px`,
                          '--ar': `${p.ar}deg`,
                          '--px': `${p.px}px`,
                          '--py': `${p.py}px`,
                          '--pr': `${p.pr}deg`,
                        } as CSSProperties)
                      : ({ animationName: 'none' } as CSSProperties)
                  }
                >
                  {letter === ' ' ? '\u00a0' : letter}
                </span>
              )
            })}
          </p>
          {!isSecretThemeUnlocked ? (
            <button
              type="button"
              className={`secret-horse click-${Math.min(horseClicks, 5)} ${
                isHorseLaunching ? 'launching' : ''
              }`}
              onClick={onSecretHorseClick}
              aria-label="Secret easter egg"
            >
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <rect
                  x="5"
                  y="5"
                  width="14"
                  height="14"
                  rx="4"
                  fill="rgb(255 255 255 / 0.22)"
                />
                <path
                  d="M8 9h8M8 13h5"
                  stroke="white"
                  strokeWidth="1.8"
                  strokeLinecap="round"
                />
                <circle cx="17" cy="17" r="2" fill="oklch(0.95 0.1 86)" />
              </svg>
            </button>
          ) : null}
        </div>
      ) : null}
      {messages.map((message, index) => (
        <button
          type="button"
          className={`message-row ${message.unread ? 'unread' : ''} ${
            message.id === selectedMessageId ? 'selected' : ''
          }`}
          key={message.id}
          aria-pressed={message.id === selectedMessageId}
          onClick={() => onSelectMessage(message.id)}
        >
          <span className="cell centered">
            {message.unread ? (
              <span className="unread-dot" aria-label="Unread" />
            ) : null}
          </span>
          <span className="cell centered">
            {message.flagged ? <Star aria-label="Flagged" /> : null}
          </span>
          <span className="cell centered">
            {index === 1 ? <Paperclip aria-label="Has attachment" /> : null}
          </span>
          <span className="cell message-subject">
            <strong>{message.subject}</strong>
          </span>
          <span className="cell message-from">{message.from}</span>
          <time className="cell">Today&nbsp;&nbsp;{message.time}</time>
          <span className="cell message-source">Stalwart</span>
        </button>
      ))}
      {!isZeroInbox ? (
        <div className="list-skeleton" aria-hidden="true">
          <span />
          <span />
          <span />
          <span />
        </div>
      ) : null}
    </section>
  )
}
