// The wire protocol as TypeScript: generated by the models crate's export-ts
// (`just gen-ts`) into ./gen — never hand-written. Source-form exports; bun
// and vite consume the .ts directly, so there is no build step.
export * from './gen/index'
