export const LOG_EVENTS = {
  apiRequestCompleted: 'api.request.completed',
  apiRequestFailed: 'api.request.failed',
  apiRequestStarted: 'api.request.started',
  daemonEventMalformed: 'daemon.event.malformed',
  dockBadgeUpdateFailed: 'dock.badge.update.failed',
  daemonEventStreamError: 'daemon.event.stream_error',
  frontendConsoleOutput: 'frontend.console.output',
  frontendErrorUncaught: 'frontend.error.uncaught',
  frontendErrorUnhandledRejection: 'frontend.error.unhandled_rejection',
  historyApplyDiffDispatched: 'history.apply_diff.dispatched',
  historyNavigationDropped: 'history.navigation.dropped',
  historyRedoRequested: 'history.redo.requested',
  historyUndoRequested: 'history.undo.requested',
  outboxRehydrateDropped: 'outbox.rehydrate.dropped',
  outboxRehydrateResent: 'outbox.rehydrate.resent',
  outboxRehydrateSkipped: 'outbox.rehydrate.skipped',
  outboxWriteFailed: 'outbox.write.failed',
  paletteProviderCompleted: 'palette.provider.completed',
  paletteProviderFailed: 'palette.provider.failed',
  paletteSearchCancelled: 'palette.search.cancelled',
  paletteSearchStale: 'palette.search.stale',
  databaseRepairFailed: 'database.repair.failed',
  diagnosticsCopied: 'diagnostics.copied',
  diagnosticsCopyFailed: 'diagnostics.copy.failed',
  replicaDatabaseBlocked: 'replica.database.blocked',
  replicaDatabaseOutdated: 'replica.database.outdated',
  replicaUnloadFlushFailed: 'replica.unload.flush_failed',
  replicaWorkerRestarted: 'replica.worker.restarted',
  resourceFetchError: 'resource.fetch.error',
  runtimeAdapterInitialized: 'runtime.adapter.initialized',
  runtimeFrameDispatched: 'runtime.frame.dispatched',
  runtimeMutationSent: 'runtime.mutation.sent',
  runtimeMutationRejected: 'runtime.mutation.rejected',
  runtimeReplicaAdapterInstalled: 'runtime.adapter.replica_installed',
  uiShortcutKeyPressed: 'ui.shortcut.key.pressed',
  updateCheckFailed: 'update.check.failed',
  updateInstallFailed: 'update.install.failed',
  viewDeltaApplied: 'view.delta.applied',
  viewExtendFailed: 'view.extend.failed',
  viewOpenFailed: 'view.open.failed',
  viewSnapshotApplied: 'view.snapshot.applied',
} as const

export type LogEvent = (typeof LOG_EVENTS)[keyof typeof LOG_EVENTS]
