export const LOG_EVENTS = {
  apiRequestCompleted: 'api.request.completed',
  apiRequestFailed: 'api.request.failed',
  apiRequestStarted: 'api.request.started',
  daemonEventMalformed: 'daemon.event.malformed',
  daemonEventStreamError: 'daemon.event.stream_error',
  frontendConsoleOutput: 'frontend.console.output',
  frontendErrorUncaught: 'frontend.error.uncaught',
  frontendErrorUnhandledRejection: 'frontend.error.unhandled_rejection',
  historyApplyDiffDispatched: 'history.apply_diff.dispatched',
  historyNavigationDropped: 'history.navigation.dropped',
  historyRedoRequested: 'history.redo.requested',
  historyUndoRequested: 'history.undo.requested',
  paletteProviderCompleted: 'palette.provider.completed',
  paletteProviderFailed: 'palette.provider.failed',
  paletteSearchCancelled: 'palette.search.cancelled',
  paletteSearchStale: 'palette.search.stale',
  databaseRepairFailed: 'database.repair.failed',
  resourceFetchError: 'resource.fetch.error',
  runtimeAdapterInitialized: 'runtime.adapter.initialized',
  runtimeFrameDispatched: 'runtime.frame.dispatched',
  runtimeMutationSent: 'runtime.mutation.sent',
  runtimeReplicaAdapterInstalled: 'runtime.adapter.replica_installed',
  uiShortcutKeyPressed: 'ui.shortcut.key.pressed',
  updateCheckFailed: 'update.check.failed',
  updateInstallFailed: 'update.install.failed',
  viewDeltaApplied: 'view.delta.applied',
  viewSnapshotApplied: 'view.snapshot.applied',
} as const

export type LogEvent = (typeof LOG_EVENTS)[keyof typeof LOG_EVENTS]
