[package]
name = "posthaste-imap"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
async-stream = "0.3"
base64 = { workspace = true }
hex = { workspace = true }
imap-client = { workspace = true }
imap-codec = "2.0.0-alpha.7"
lettre = { workspace = true }
mail-parser = { workspace = true }
posthaste-domain-service = { path = "../posthaste-domain-service" }
posthaste-observability = { path = "../posthaste-observability" }
pulldown-cmark = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
