#!/usr/bin/env bash
# Launch the PostHaste dev stack with Overmind.
#
# Usage: launch.sh <web|desktop|services>
#
# Defaults point the server at an isolated dev-only config/state root
# (var/dev/posthaste/) so the real ~/.config/posthaste is never touched.
# Override any POSTHASTE_* env var before invoking to change behavior.
set -euo pipefail

layout="${1:?usage: launch.sh <web|desktop|services>}"
case "$layout" in
  web|desktop|services) ;;
  *) echo "unknown layout: $layout (expected web|desktop|services)" >&2; exit 2 ;;
esac

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$root"

port_is_available() {
  local port="$1"
  node -e '
const net = require("node:net");
const port = Number(process.argv[1]);
const hosts = ["127.0.0.1", "::1"];

function canBind(host) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once("error", (error) => {
      resolve(error.code === "EADDRNOTAVAIL");
    });
    server.once("listening", () => {
      server.close(() => resolve(true));
    });
    server.listen(port, host);
  });
}

Promise.all(hosts.map(canBind)).then((results) => {
  process.exit(results.every(Boolean) ? 0 : 1);
});
' "$port" >/dev/null 2>&1
}

find_available_port() {
  local port="${1:?base port required}"
  local max_port=$((port + 200))

  while (( port <= max_port )); do
    if port_is_available "$port"; then
      printf '%s\n' "$port"
      return 0
    fi
    port=$((port + 1))
  done

  echo "no available port found in range $1-$max_port" >&2
  return 1
}

port_from_bind() {
  local bind="${1:?bind address required}"
  printf '%s\n' "${bind##*:}"
}

export POSTHASTE_STALWART_ADMIN_PASSWORD="${POSTHASTE_STALWART_ADMIN_PASSWORD:-devadmin}"
export POSTHASTE_STALWART_USER_PASSWORD="${POSTHASTE_STALWART_USER_PASSWORD:-devpass}"

if [[ -z "${POSTHASTE_STALWART_BIND:-}" ]]; then
  POSTHASTE_STALWART_PORT="$(find_available_port 8080)"
  export POSTHASTE_STALWART_BIND="127.0.0.1:$POSTHASTE_STALWART_PORT"
else
  POSTHASTE_STALWART_PORT="$(port_from_bind "$POSTHASTE_STALWART_BIND")"
fi
export POSTHASTE_STALWART_URL="${POSTHASTE_STALWART_URL:-http://127.0.0.1:$POSTHASTE_STALWART_PORT}"

if [[ -z "${POSTHASTE_BIND:-}" ]]; then
  POSTHASTE_SERVER_PORT="$(find_available_port 3001)"
  export POSTHASTE_BIND="127.0.0.1:$POSTHASTE_SERVER_PORT"
else
  POSTHASTE_SERVER_PORT="$(port_from_bind "$POSTHASTE_BIND")"
fi

export POSTHASTE_VITE_HOST="${POSTHASTE_VITE_HOST:-127.0.0.1}"
if [[ "$layout" == "desktop" ]]; then
  if [[ -n "${POSTHASTE_VITE_PORT:-}" && "$POSTHASTE_VITE_PORT" != "5173" ]]; then
    echo "desktop dev uses Tauri devUrl http://127.0.0.1:5173; unset POSTHASTE_VITE_PORT or set it to 5173" >&2
    exit 2
  fi
  export POSTHASTE_VITE_PORT="5173"
elif [[ -z "${POSTHASTE_VITE_PORT:-}" ]]; then
  export POSTHASTE_VITE_PORT="$(find_available_port 5173)"
fi
export VITE_API_BASE_URL="${VITE_API_BASE_URL:-http://127.0.0.1:$POSTHASTE_SERVER_PORT/v1}"
export POSTHASTE_CORS_ORIGIN="${POSTHASTE_CORS_ORIGIN:-http://$POSTHASTE_VITE_HOST:$POSTHASTE_VITE_PORT}"

instance_id="mail${POSTHASTE_STALWART_PORT}-api${POSTHASTE_SERVER_PORT}-web${POSTHASTE_VITE_PORT}"
use_instance_roots=false
if [[ "$POSTHASTE_STALWART_PORT" != "8080" || "$POSTHASTE_SERVER_PORT" != "3001" || "$POSTHASTE_VITE_PORT" != "5173" ]]; then
  use_instance_roots=true
fi

if [[ "$use_instance_roots" == "true" ]]; then
  instance_root="$root/var/dev/instances/$instance_id"
  export POSTHASTE_STALWART_DATA="${POSTHASTE_STALWART_DATA:-$instance_root/stalwart/data}"
  export POSTHASTE_STALWART_LOGS="${POSTHASTE_STALWART_LOGS:-$instance_root/stalwart/logs}"
  export POSTHASTE_CONFIG_ROOT="${POSTHASTE_CONFIG_ROOT:-$instance_root/posthaste/config}"
  export POSTHASTE_STATE_ROOT="${POSTHASTE_STATE_ROOT:-$instance_root/posthaste/state}"
else
  export POSTHASTE_STALWART_DATA="${POSTHASTE_STALWART_DATA:-$root/var/dev/stalwart/data}"
  export POSTHASTE_STALWART_LOGS="${POSTHASTE_STALWART_LOGS:-$root/var/dev/stalwart/logs}"
  export POSTHASTE_CONFIG_ROOT="${POSTHASTE_CONFIG_ROOT:-$root/var/dev/posthaste/config}"
  export POSTHASTE_STATE_ROOT="${POSTHASTE_STATE_ROOT:-$root/var/dev/posthaste/state}"
fi

if [[ -z "${POSTHASTE_BOOTSTRAP_PATH:-}" ]]; then
  generated_dir="$POSTHASTE_STATE_ROOT/generated"
  mkdir -p "$generated_dir"
  generated_bootstrap="$generated_dir/bootstrap.stalwart.toml"
  cat > "$generated_bootstrap" <<EOF
# Generated by tools/dev/overmind/launch.sh for $instance_id.

[seed.app]
defaultAccountId = "local-stalwart"

[[seed.accounts]]
id = "local-stalwart"
name = "Local Stalwart"
driver = "jmap"
enabled = true

[seed.accounts.transport]
baseUrl = "$POSTHASTE_STALWART_URL"
username = "dev"

[seed.accounts.transport.secretRef]
kind = "env"
key = "POSTHASTE_STALWART_USER_PASSWORD"
EOF
  export POSTHASTE_BOOTSTRAP_PATH="$generated_bootstrap"
fi

mkdir -p \
  "$POSTHASTE_STALWART_DATA" "$POSTHASTE_STALWART_LOGS" \
  "$POSTHASTE_CONFIG_ROOT" "$POSTHASTE_STATE_ROOT"
rm -f "$POSTHASTE_STATE_ROOT/.stalwart-seed-ready"

log_path="$("$root/tools/dev/overmind/server-log-path.sh")"
echo "Persisted server log: $log_path (tail with 'just server-log-tail')"
echo "Dev ports: Stalwart $POSTHASTE_STALWART_URL, API http://127.0.0.1:$POSTHASTE_SERVER_PORT, Web http://$POSTHASTE_VITE_HOST:$POSTHASTE_VITE_PORT"

if [[ "${POSTHASTE_DEV_STACK_SMOKE:-}" == "1" ]]; then
  require_var_dev_path() {
    local label="${1:?label required}"
    local path="${2:?path required}"
    case "$path" in
      "$root"/var/dev/*) ;;
      *) echo "$label must stay under var/dev: $path" >&2; exit 1 ;;
    esac
  }

  require_var_dev_path "Stalwart data" "$POSTHASTE_STALWART_DATA"
  require_var_dev_path "Stalwart logs" "$POSTHASTE_STALWART_LOGS"
  require_var_dev_path "PostHaste config" "$POSTHASTE_CONFIG_ROOT"
  require_var_dev_path "PostHaste state" "$POSTHASTE_STATE_ROOT"
  require_var_dev_path "Generated bootstrap" "$POSTHASTE_BOOTSTRAP_PATH"
  [[ -f "tools/dev/Procfile.$layout" ]] || { echo "missing Procfile for $layout" >&2; exit 1; }
  [[ -f "$POSTHASTE_BOOTSTRAP_PATH" ]] || { echo "missing generated bootstrap: $POSTHASTE_BOOTSTRAP_PATH" >&2; exit 1; }
  echo "Dev stack smoke passed for $layout."
  exit 0
fi

if ! command -v overmind >/dev/null 2>&1; then
  echo "overmind is not on PATH; reload the Nix dev shell with 'direnv reload' or 'nix develop'." >&2
  exit 127
fi

overmind_socket="$root/.overmind.$instance_id.sock"
exec overmind start \
  -d "$root" \
  -N \
  -c seed \
  -f "tools/dev/Procfile.$layout" \
  -s "$overmind_socket" \
  -w "posthaste-$instance_id"
