import {
  Archive,
  ChevronDown,
  Circle,
  Flag,
  Inbox,
  Paperclip,
  Star,
} from 'lucide-react'
import {
  type CSSProperties,
  useEffect,
  useLayoutEffect,
  useMemo,
  useState,
} from 'react'
import type { HomeContent, SiteMessage } from './content/types'
import { FooterSection, InstallHeader } from './SiteChrome'

// Auto-generated by apps/site/tools/gen-collision-keyframes.mjs (v3)
// Snowplow model: all letters scatter rightward; cascade resolves overlaps.
// ax/ay/ar = position at 40 % of scatter animation (arc peak)
// px/py/pr = final resting position (100 %)
// prettier-ignore
const LETTER_PHYSICS = [
  { delay: 354, ax:  106, ay:  -18, ar:  -19.5, px:  163, py:  -27, pr:  -29.9 }, // A
  { delay: 387, ax:   95, ay:   10, ar:   14.6, px:  145, py:   16, pr:   22.4 }, // l
  { delay: 405, ax:  104, ay:  -26, ar:  -25.6, px:  159, py:  -40, pr:  -39.2 }, // l
  { delay: 424, ax:  114, ay:  -18, ar:  -19.1, px:  175, py:  -28, pr:  -29.3 }, // (space)
  { delay: 455, ax:  120, ay:  -26, ar:  -25.8, px:  184, py:  -41, pr:  -39.5 }, // q
  { delay: 497, ax:  120, ay:  -10, ar:  -10.5, px:  184, py:  -15, pr:  -16.2 }, // u
  { delay: 526, ax:  112, ay:    8, ar:   17.9, px:  172, py:   12, pr:   27.5 }, // i
  { delay: 553, ax:   93, ay:   11, ar:   18.6, px:  143, py:   17, pr:   28.5 }, // e
  { delay: 585, ax:  102, ay:  -22, ar:  -19.8, px:  157, py:  -33, pr:  -30.3 }, // t
  { delay: 606, ax:  107, ay:  -22, ar:    -20, px:  165, py:  -34, pr:  -30.7 }, // !
  { delay: 623, ax:  101, ay:   20, ar:   23.8, px:  155, py:   31, pr:   36.5 }, // (space)
  { delay: 657, ax:  106, ay:   21, ar:   22.3, px:  163, py:   32, pr:   34.1 }, // Z
  { delay: 700, ax:  113, ay:   -3, ar:  -13.1, px:  173, py:   -4, pr:    -20 }, // e
  { delay: 733, ax:  109, ay:   -2, ar:   -7.6, px:  167, py:   -4, pr:  -11.6 }, // r
  { delay: 767, ax:   84, ay:   14, ar:   14.4, px:  129, py:   22, pr:     22 }, // o
  { delay: 798, ax:  104, ay:   24, ar:     21, px:  160, py:   36, pr:   32.2 }, // (space)
  { delay: 815, ax:   82, ay:  -16, ar:  -20.4, px:  126, py:  -24, pr:  -31.2 }, // i
  { delay: 844, ax:  104, ay:   -6, ar:    -16, px:  159, py:  -10, pr:  -24.5 }, // n
  { delay: 886, ax:   94, ay:   27, ar:   22.2, px:  143, py:   41, pr:   34.1 }, // b
  { delay: 928, ax:   75, ay:   -9, ar:  -13.4, px:  114, py:  -14, pr:  -20.6 }, // o
  { delay: 969, ax:   82, ay:   23, ar:   19.9, px:  126, py:   36, pr:   30.5 }, // x
] as const

interface Mailbox {
  id: 'inbox' | 'archive'
  label: string
  count: string
  active?: boolean
}

type MailboxView = Mailbox['id']
type MockTheme = 'baseline' | 'glass' | 'typewriter' | 'pigeon'

interface PersistedMockState {
  selectedMailbox?: MailboxView
  selectedMessageId?: string | null
  readMessageIds?: string[]
  archivedMessageIds?: string[]
  flaggedMessageIds?: string[]
  mockTheme?: MockTheme
  hasUnlockedSecretTheme?: boolean
}

interface MessagePreview extends SiteMessage {
  archived: boolean
  flagged: boolean
}

type LandscapePhase = 'night' | 'morning' | 'day' | 'evening'

interface LandscapeTimeState {
  phase: LandscapePhase
  celestialX: number
  celestialY: number
}

const initialLandscapeTimeState: LandscapeTimeState = {
  phase: 'day',
  celestialX: 41,
  celestialY: 22,
}

function mailboxCounts(messages: MessagePreview[]) {
  return {
    inbox: messages.filter((message) => !message.archived && message.unread)
      .length,
    archive: messages.filter((message) => message.archived && message.unread)
      .length,
  }
}

const palette = ['blue', 'coral', 'sage', 'amber', 'violet']
const MOCK_STATE_STORAGE_KEY = 'posthaste-site-mail-mock-state-v1'

function loadPersistedMockState(): PersistedMockState {
  if (typeof window === 'undefined') return {}

  const raw = window.localStorage.getItem(MOCK_STATE_STORAGE_KEY)
  if (!raw) return {}

  try {
    const parsed = JSON.parse(raw) as PersistedMockState
    return parsed && typeof parsed === 'object' ? parsed : {}
  } catch {
    return {}
  }
}

function persistedSet(values: string[] | undefined): ReadonlySet<string> {
  return new Set(values ?? [])
}

function isMockTheme(value: unknown): value is MockTheme {
  return (
    value === 'baseline' ||
    value === 'glass' ||
    value === 'typewriter' ||
    value === 'pigeon'
  )
}

function getLandscapeTimeState(date = new Date()): LandscapeTimeState {
  const minutes = date.getHours() * 60 + date.getMinutes()
  const sunrise = 6 * 60
  const morningEnd = 10 * 60
  const eveningStart = 17 * 60
  const sunset = 20 * 60

  let phase: LandscapePhase = 'night'

  if (minutes >= sunrise && minutes < morningEnd) {
    phase = 'morning'
  } else if (minutes >= morningEnd && minutes < eveningStart) {
    phase = 'day'
  } else if (minutes >= eveningStart && minutes < sunset) {
    phase = 'evening'
  }

  if (phase === 'night') {
    const nightStart = sunset
    const nightLength = 10 * 60
    const nightMinutes =
      minutes >= nightStart
        ? minutes - nightStart
        : minutes + 24 * 60 - nightStart
    const progress = nightMinutes / nightLength

    return {
      phase,
      celestialX: 8 + progress * 84,
      celestialY: 66 - Math.sin(progress * Math.PI) * 34,
    }
  }

  const dayProgress = Math.max(
    0,
    Math.min(1, (minutes - sunrise) / (sunset - sunrise)),
  )

  return {
    phase,
    celestialX: 8 + dayProgress * 66,
    celestialY: 72 - Math.sin(dayProgress * Math.PI) * 50,
  }
}

function useLandscapeTime() {
  const [timeState, setTimeState] = useState(initialLandscapeTimeState)

  useEffect(() => {
    const initial = window.setTimeout(() => {
      setTimeState(getLandscapeTimeState())
    }, 0)
    const interval = window.setInterval(() => {
      setTimeState(getLandscapeTimeState())
    }, 60_000)

    return () => {
      window.clearTimeout(initial)
      window.clearInterval(interval)
    }
  }, [])

  return timeState
}

function useReveal() {
  useEffect(() => {
    const reduceMotion = window.matchMedia(
      '(prefers-reduced-motion: reduce)',
    ).matches

    if (reduceMotion) {
      document
        .querySelectorAll<HTMLElement>('[data-reveal]')
        .forEach((element) => element.classList.add('is-visible'))
      return
    }

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible')
          }
        })
      },
      { rootMargin: '0px 0px -10% 0px', threshold: 0.18 },
    )

    document
      .querySelectorAll<HTMLElement>('[data-reveal]')
      .forEach((element) => observer.observe(element))

    return () => observer.disconnect()
  }, [])
}

export function App({ content }: { content: HomeContent }) {
  useLayoutEffect(() => {
    document.documentElement.classList.add('mail-mock-hydrated')

    return () => {
      document.documentElement.classList.remove('mail-mock-hydrated')
    }
  }, [])
  useReveal()

  return (
    <main className="site-shell">
      <InstallHeader />
      <Hero messages={content.messages} />
      <LandscapeValuesSection content={content.openSource} />
      <NotesSection content={content} />
      <ThemeSection content={content.theme} />
      <FooterSection content={content.footer} />
    </main>
  )
}

function Hero({ messages }: { messages: SiteMessage[] }) {
  const persistedState = useMemo(() => loadPersistedMockState(), [])
  const [selectedMailbox, setSelectedMailbox] = useState<MailboxView>(
    persistedState.selectedMailbox === 'archive' ? 'archive' : 'inbox',
  )
  const [selectedMessageId, setSelectedMessageId] = useState<string | null>(
    persistedState.selectedMessageId ?? messages[0]?.id ?? null,
  )
  const [readMessageIds, setReadMessageIds] = useState<ReadonlySet<string>>(
    () => persistedSet(persistedState.readMessageIds),
  )
  const [archivedMessageIds, setArchivedMessageIds] = useState<
    ReadonlySet<string>
  >(() => persistedSet(persistedState.archivedMessageIds))
  const [flaggedMessageIds, setFlaggedMessageIds] = useState<
    ReadonlySet<string>
  >(() => persistedSet(persistedState.flaggedMessageIds))
  const [mockTheme, setMockTheme] = useState<MockTheme>(
    isMockTheme(persistedState.mockTheme)
      ? persistedState.mockTheme
      : 'baseline',
  )
  const [hasUnlockedSecretTheme, setHasUnlockedSecretTheme] = useState(
    persistedState.hasUnlockedSecretTheme === true,
  )
  const [horseClicks, setHorseClicks] = useState(0)
  const [isHorseLaunching, setIsHorseLaunching] = useState(false)
  const previewMessages = useMemo<MessagePreview[]>(
    () =>
      messages.map((message) => ({
        ...message,
        archived: archivedMessageIds.has(message.id),
        flagged: flaggedMessageIds.has(message.id),
        unread: !readMessageIds.has(message.id),
      })),
    [archivedMessageIds, flaggedMessageIds, messages, readMessageIds],
  )
  const visibleMessages = useMemo(
    () =>
      previewMessages.filter((message) =>
        selectedMailbox === 'archive' ? message.archived : !message.archived,
      ),
    [previewMessages, selectedMailbox],
  )
  const selectedMessage =
    visibleMessages.find((message) => message.id === selectedMessageId) ??
    visibleMessages[0] ??
    null
  const counts = mailboxCounts(previewMessages)

  // Propagate mock theme to <html> so the rest of the page adopts it.
  useEffect(() => {
    const html = document.documentElement
    html.classList.remove('theme-glass', 'theme-typewriter', 'theme-pigeon')
    if (mockTheme !== 'baseline') {
      html.classList.add(`theme-${mockTheme}`)
    }
    return () => {
      html.classList.remove('theme-glass', 'theme-typewriter', 'theme-pigeon')
    }
  }, [mockTheme])

  useEffect(() => {
    const state: PersistedMockState = {
      selectedMailbox,
      selectedMessageId,
      readMessageIds: [...readMessageIds],
      archivedMessageIds: [...archivedMessageIds],
      flaggedMessageIds: [...flaggedMessageIds],
      mockTheme,
      hasUnlockedSecretTheme,
    }
    window.localStorage.setItem(MOCK_STATE_STORAGE_KEY, JSON.stringify(state))
  }, [
    archivedMessageIds,
    flaggedMessageIds,
    hasUnlockedSecretTheme,
    mockTheme,
    readMessageIds,
    selectedMailbox,
    selectedMessageId,
  ])

  function handleSelectMessage(messageId: string) {
    setSelectedMessageId(messageId)
    setReadMessageIds((current) => new Set(current).add(messageId))
  }

  function handleSelectMailbox(mailbox: MailboxView) {
    setSelectedMailbox(mailbox)
    const nextMessage = previewMessages.find((message) =>
      mailbox === 'archive' ? message.archived : !message.archived,
    )
    setSelectedMessageId(nextMessage?.id ?? null)
    if (nextMessage) {
      setReadMessageIds((current) => new Set(current).add(nextMessage.id))
    }
  }

  function handleArchiveSelected() {
    if (!selectedMessage || selectedMessage.archived) return
    const nextMessage = visibleMessages.find(
      (message) => message.id !== selectedMessage.id,
    )
    setArchivedMessageIds((current) => new Set(current).add(selectedMessage.id))
    setSelectedMessageId(nextMessage?.id ?? null)
    if (nextMessage) {
      setReadMessageIds((current) => new Set(current).add(nextMessage.id))
    }
  }

  function handleToggleFlagSelected() {
    if (!selectedMessage) return
    setFlaggedMessageIds((current) => {
      const next = new Set(current)
      if (next.has(selectedMessage.id)) {
        next.delete(selectedMessage.id)
      } else {
        next.add(selectedMessage.id)
      }
      return next
    })
  }

  function handleSecretHorseClick() {
    if (hasUnlockedSecretTheme || isHorseLaunching) return

    const nextClicks = horseClicks + 1
    setHorseClicks(nextClicks)
    if (nextClicks < 5) return

    setIsHorseLaunching(true)
    window.setTimeout(() => {
      setHasUnlockedSecretTheme(true)
      setIsHorseLaunching(false)
    }, 1200)
  }

  return (
    <section className="hero" aria-labelledby="hero-title">
      <div className={`client-frame theme-${mockTheme} is-visible`} data-reveal>
        <ClientToolbar
          canArchive={selectedMailbox === 'inbox' && selectedMessage !== null}
          isFlagged={selectedMessage?.flagged ?? false}
          isMessageSelected={selectedMessage !== null}
          onArchive={handleArchiveSelected}
          selectedTheme={mockTheme}
          isSecretThemeUnlocked={hasUnlockedSecretTheme}
          onSelectTheme={setMockTheme}
          onToggleFlag={handleToggleFlagSelected}
        />
        <div className="client-body">
          <SidebarPreview
            counts={counts}
            selectedMailbox={selectedMailbox}
            onSelectMailbox={handleSelectMailbox}
          />
          <MessageListPreview
            messages={visibleMessages}
            selectedMessageId={selectedMessage?.id ?? null}
            selectedMailbox={selectedMailbox}
            horseClicks={horseClicks}
            isHorseLaunching={isHorseLaunching}
            isSecretThemeUnlocked={hasUnlockedSecretTheme}
            onSecretHorseClick={handleSecretHorseClick}
            onSelectMessage={handleSelectMessage}
          />
          <ReaderPreview message={selectedMessage} />
        </div>
      </div>
    </section>
  )
}

function ClientToolbar({
  canArchive,
  isFlagged,
  isMessageSelected,
  selectedTheme,
  isSecretThemeUnlocked,
  onArchive,
  onSelectTheme,
  onToggleFlag,
}: {
  canArchive: boolean
  isFlagged: boolean
  isMessageSelected: boolean
  selectedTheme: MockTheme
  isSecretThemeUnlocked: boolean
  onArchive: () => void
  onSelectTheme: (theme: MockTheme) => void
  onToggleFlag: () => void
}) {
  const themes: { id: MockTheme; label: string }[] = [
    { id: 'baseline', label: 'Baseline' },
    { id: 'glass', label: 'Glass' },
    { id: 'typewriter', label: 'Typewriter' },
  ]
  if (isSecretThemeUnlocked) {
    themes.push({ id: 'pigeon', label: 'Pigeon' })
  }

  return (
    <nav className="client-toolbar" aria-label="Primary">
      <div className="traffic-lights" aria-hidden="true">
        <span />
        <span />
        <span />
      </div>
      <button
        type="button"
        className="toolbar-action"
        disabled={!canArchive}
        onClick={onArchive}
        title="Archive"
      >
        <Archive aria-hidden="true" />
      </button>
      <button
        type="button"
        className={`toolbar-action ${isFlagged ? 'active' : ''}`}
        disabled={!isMessageSelected}
        onClick={onToggleFlag}
        title="Flag"
      >
        <Flag aria-hidden="true" />
      </button>
      <div className="toolbar-spacer" />
      <div className="theme-switcher" aria-label="Mock theme switcher">
        {themes.map((theme) => (
          <button
            type="button"
            className={`theme-chip ${theme.id === selectedTheme ? 'active' : ''} ${
              theme.id === 'pigeon' ? 'secret' : ''
            }`}
            key={theme.id}
            aria-label={`${theme.label} theme`}
            title={theme.label}
            onClick={() => onSelectTheme(theme.id)}
          >
            <ThemeIcon theme={theme.id} />
          </button>
        ))}
      </div>
    </nav>
  )
}

function ThemeIcon({ theme }: { theme: MockTheme }) {
  if (theme === 'glass') {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <defs>
          <linearGradient id="theme-glass" x1="4" y1="4" x2="20" y2="20">
            <stop stopColor="#9ad7ff" />
            <stop offset="0.52" stopColor="#f4b6ff" />
            <stop offset="1" stopColor="#ffe28a" />
          </linearGradient>
        </defs>
        <rect
          x="5"
          y="4"
          width="14"
          height="16"
          rx="4"
          fill="url(#theme-glass)"
          opacity="0.72"
        />
        <path
          d="M8 8h8M8 12h5"
          stroke="white"
          strokeWidth="1.8"
          strokeLinecap="round"
          opacity="0.9"
        />
      </svg>
    )
  }

  if (theme === 'typewriter') {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect x="4" y="7" width="16" height="10" rx="2" fill="#f1e4c6" />
        <path
          d="M7 7V5h10v2M7 13h10M8 17h8"
          stroke="#3d3328"
          strokeWidth="1.6"
          strokeLinecap="round"
        />
        <circle cx="8" cy="10" r="1" fill="#3d3328" />
        <circle cx="12" cy="10" r="1" fill="#3d3328" />
        <circle cx="16" cy="10" r="1" fill="#3d3328" />
      </svg>
    )
  }

  if (theme === 'pigeon') {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect
          x="5"
          y="5"
          width="14"
          height="14"
          rx="4"
          fill="oklch(0.38 0.12 295)"
        />
        <path
          d="M8 9h8M8 13h5"
          stroke="oklch(0.72 0.08 295)"
          strokeWidth="1.8"
          strokeLinecap="round"
        />
        <circle cx="17" cy="17" r="2" fill="oklch(0.74 0.14 50)" />
      </svg>
    )
  }

  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <rect x="5" y="5" width="14" height="14" rx="4" fill="#2f3436" />
      <path
        d="M8 9h8M8 13h5"
        stroke="#f4f1ea"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
      <circle cx="17" cy="17" r="2" fill="#d67850" />
    </svg>
  )
}

function SidebarPreview({
  counts,
  selectedMailbox,
  onSelectMailbox,
}: {
  counts: ReturnType<typeof mailboxCounts>
  selectedMailbox: MailboxView
  onSelectMailbox: (mailbox: MailboxView) => void
}) {
  const [isExpanded, setIsExpanded] = useState(true)
  const mailboxes: Mailbox[] = [
    {
      id: 'inbox',
      label: 'Inbox',
      count: String(counts.inbox),
      active: selectedMailbox === 'inbox',
    },
    {
      id: 'archive',
      label: 'Archive',
      count: String(counts.archive),
      active: selectedMailbox === 'archive',
    },
  ]

  return (
    <aside className="mock-sidebar" aria-label="Mailbox preview">
      <SidebarSection label="Accounts" />
      <div className="source-section">
        <button
          type="button"
          className="source-header"
          aria-expanded={isExpanded}
          onClick={() => setIsExpanded((current) => !current)}
        >
          <ChevronDown aria-hidden="true" />
          <span className="account-stamp stalwart">S</span>
          <span>Stalwart</span>
          {counts.inbox > 0 ? (
            <span className="source-count">{counts.inbox}</span>
          ) : null}
        </button>
        {isExpanded
          ? mailboxes.map((mailbox) => (
              <SidebarItem
                mailbox={mailbox}
                key={mailbox.id}
                onSelect={() => onSelectMailbox(mailbox.id)}
              />
            ))
          : null}
      </div>
    </aside>
  )
}

function SidebarSection({ label }: { label: string }) {
  return <div className="section-label">{label}</div>
}

function SidebarItem({
  mailbox,
  onSelect,
}: {
  mailbox: Mailbox
  onSelect: () => void
}) {
  const Icon = mailbox.id === 'archive' ? Archive : Inbox

  return (
    <button
      type="button"
      className={`mailbox-row nested ${mailbox.active ? 'active' : ''}`}
      onClick={onSelect}
    >
      <Icon aria-hidden="true" />
      <span>{mailbox.label}</span>
      {Number(mailbox.count) > 0 ? (
        <span className="count">{mailbox.count}</span>
      ) : null}
    </button>
  )
}

function MessageListPreview({
  messages,
  selectedMessageId,
  selectedMailbox,
  horseClicks,
  isHorseLaunching,
  isSecretThemeUnlocked,
  onSecretHorseClick,
  onSelectMessage,
}: {
  messages: MessagePreview[]
  selectedMessageId: string | null
  selectedMailbox: MailboxView
  horseClicks: number
  isHorseLaunching: boolean
  isSecretThemeUnlocked: boolean
  onSecretHorseClick: () => void
  onSelectMessage: (messageId: string) => void
}) {
  const isZeroInbox = selectedMailbox === 'inbox' && messages.length === 0

  const scatterActive = isZeroInbox && !isSecretThemeUnlocked

  return (
    <section className="mock-list" aria-label="Conversation list preview">
      <div className="list-heading">
        <span aria-label="Unread">
          <Circle aria-hidden="true" />
        </span>
        <span aria-label="Flagged">
          <Star aria-hidden="true" />
        </span>
        <span aria-label="Attachment">
          <Paperclip aria-hidden="true" />
        </span>
        <span>Subject</span>
        <span>From</span>
        <span>Date received</span>
        <span>Account</span>
      </div>
      {isZeroInbox ? (
        <div className="zero-inbox-stage">
          <p className="zero-inbox-letters" aria-label="All quiet! Zero inbox">
            {'All quiet! Zero inbox'.split('').map((letter, index) => {
              const p = LETTER_PHYSICS[index]
              return (
                <span
                  key={`${letter}-${index}`}
                  style={
                    scatterActive
                      ? ({
                          animationDelay: `${p.delay}ms`,
                          '--ax': `${p.ax}px`,
                          '--ay': `${p.ay}px`,
                          '--ar': `${p.ar}deg`,
                          '--px': `${p.px}px`,
                          '--py': `${p.py}px`,
                          '--pr': `${p.pr}deg`,
                        } as CSSProperties)
                      : ({ animationName: 'none' } as CSSProperties)
                  }
                >
                  {letter === ' ' ? '\u00a0' : letter}
                </span>
              )
            })}
          </p>
          {!isSecretThemeUnlocked ? (
            <button
              type="button"
              className={`secret-horse click-${Math.min(horseClicks, 5)} ${
                isHorseLaunching ? 'launching' : ''
              }`}
              onClick={onSecretHorseClick}
              aria-label="Secret easter egg"
            >
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <rect
                  x="5"
                  y="5"
                  width="14"
                  height="14"
                  rx="4"
                  fill="rgb(255 255 255 / 0.22)"
                />
                <path
                  d="M8 9h8M8 13h5"
                  stroke="white"
                  strokeWidth="1.8"
                  strokeLinecap="round"
                />
                <circle cx="17" cy="17" r="2" fill="oklch(0.95 0.1 86)" />
              </svg>
            </button>
          ) : null}
        </div>
      ) : null}
      {messages.map((message, index) => (
        <button
          type="button"
          className={`message-row ${message.unread ? 'unread' : ''} ${
            message.id === selectedMessageId ? 'selected' : ''
          }`}
          key={message.id}
          aria-pressed={message.id === selectedMessageId}
          onClick={() => onSelectMessage(message.id)}
        >
          <span className="cell centered">
            {message.unread ? (
              <span className="unread-dot" aria-label="Unread" />
            ) : null}
          </span>
          <span className="cell centered">
            {message.flagged ? <Star aria-label="Flagged" /> : null}
          </span>
          <span className="cell centered">
            {index === 1 ? <Paperclip aria-label="Has attachment" /> : null}
          </span>
          <span className="cell message-subject">
            <strong>{message.subject}</strong>
          </span>
          <span className="cell message-from">{message.from}</span>
          <time className="cell">Today&nbsp;&nbsp;{message.time}</time>
          <span className="cell message-source">Stalwart</span>
        </button>
      ))}
      {!isZeroInbox ? (
        <div className="list-skeleton" aria-hidden="true">
          <span />
          <span />
          <span />
          <span />
        </div>
      ) : null}
    </section>
  )
}

function ReaderPreview({ message }: { message: MessagePreview | null }) {
  return (
    <section className="mock-reader" aria-labelledby="hero-title">
      <SloganTitle id="hero-title" />
      {message ? (
        <div className="reader-message" aria-live="polite">
          <h2>{message.subject}</h2>
          <div
            className="reader-message-body"
            dangerouslySetInnerHTML={{ __html: message.html }}
          />
        </div>
      ) : (
        <div className="reader-message zero-reader" aria-live="polite">
          <h2>No mail here.</h2>
          <p>For once, the mailbox is quieter than the keyboard.</p>
        </div>
      )}
    </section>
  )
}

function SloganTitle({ id }: { id?: string }) {
  return (
    <h1 className="slogan" id={id}>
      <span>Your email,</span>
      <span>
        delivered at Post
        <span className="letter-h">h</span>
        <span className="letter-a">a</span>
        <span className="letter-s">s</span>
        <span className="letter-t">t</span>
        <span className="letter-e">e</span>
      </span>
    </h1>
  )
}

function LandscapeValuesSection({
  content,
}: {
  content: HomeContent['openSource']
}) {
  const landscapeTime = useLandscapeTime()
  const landscapeStyle = {
    '--celestial-x': `${landscapeTime.celestialX}%`,
    '--celestial-y': `${landscapeTime.celestialY}%`,
  } as CSSProperties

  return (
    <section
      className="landscape-section"
      aria-labelledby="values-title"
      data-reveal
    >
      <div className="landscape-copy">
        <h2 id="values-title">{content.title}</h2>
        <div dangerouslySetInnerHTML={{ __html: content.html }} />
      </div>
      <div
        className={`landscape-canvas ${landscapeTime.phase}`}
        style={landscapeStyle}
        aria-hidden="true"
      >
        <span className="celestial" />
        <div className="landscape-track">
          <LandscapeSegment />
          <LandscapeSegment />
        </div>
        <img className="landscape-logo" src="/posthaste-logo.svg" alt="" />
      </div>
    </section>
  )
}

function LandscapeSegment() {
  return (
    <div className="landscape-segment">
      <svg
        className="landscape-terrain"
        viewBox="0 0 1200 260"
        preserveAspectRatio="none"
      >
        <path
          className="terrain-back"
          d="M0 148C48 132 90 130 138 146C188 164 228 167 282 150C334 134 382 120 438 142C498 166 538 181 604 160C672 138 716 121 782 146C846 170 894 183 958 158C1018 135 1066 124 1126 139C1156 147 1180 154 1200 148V260H0Z"
        />
        <path
          className="terrain-mid"
          d="M0 178C36 189 74 196 126 186C184 175 218 147 284 158C350 169 388 207 456 190C522 173 558 139 624 154C692 170 726 210 796 196C870 181 908 146 978 162C1042 177 1078 199 1136 188C1164 183 1186 174 1200 178V260H0Z"
        />
        <path
          className="terrain-front"
          d="M0 218C46 205 86 200 138 214C192 229 230 238 286 222C344 206 386 184 448 202C512 221 548 242 614 228C680 214 718 185 784 198C854 212 896 239 964 224C1028 210 1068 189 1130 203C1160 210 1184 222 1200 218V260H0Z"
        />
      </svg>
    </div>
  )
}

function NotesSection({ content }: { content: HomeContent }) {
  return (
    <section className="notes-section" id="notes" aria-labelledby="notes-title">
      <div className="section-header" data-reveal>
        <h2 id="notes-title">{content.notesHeading.title}</h2>
      </div>
      <div className="note-list">
        {content.notes.map((note) => (
          <article className="note-row" data-reveal key={note.label}>
            <span>{note.label}</span>
            <h3>{note.title}</h3>
            <div dangerouslySetInnerHTML={{ __html: note.html }} />
          </article>
        ))}
      </div>
    </section>
  )
}

function ThemeSection({ content }: { content: HomeContent['theme'] }) {
  return (
    <section
      className="theme-section"
      id="themes"
      aria-labelledby="themes-title"
    >
      <div className="theme-copy" data-reveal>
        <h2 id="themes-title">{content.title}</h2>
        <div dangerouslySetInnerHTML={{ __html: content.html }} />
      </div>
      <div className="glass-panel" data-reveal>
        <div className="glass-title">Theme preview</div>
        <div className="swatch-row" aria-hidden="true">
          {palette.map((color) => (
            <span className={color} key={color} />
          ))}
        </div>
        <div className="glass-lines" aria-hidden="true">
          <span />
          <span />
          <span />
        </div>
      </div>
    </section>
  )
}
