//! TypeScript generation: exports every wire type (and its transitive
//! dependencies) as `.ts` files plus an `index.ts` barrel.
//!
//! Generation is explicit — `cargo run -p posthaste-client-models --bin
//! export-ts` (wrapped by `just gen-ts`) writes into
//! `apps/client/frontend/src/gen/`. Tests never write into the source tree;
//! the freshness test exports into a temp directory and diffs.

use std::error::Error;
use std::fs;
use std::path::Path;

use ts_rs::TS;

use crate::{
    command::{CommandAccepted, CommandEnvelope},
    error::ApiError,
    event::EventMessage,
    mirror,
    query::{
        AccountsResult, MailListResult, MailboxCountsResult, MessageDetailResult,
        PendingOperationsResult, Query, QueryEnvelope,
    },
};

/// Exports every wire type into `dir` (created if missing), replacing any
/// `.ts` files already there, and writes the `index.ts` barrel. The output
/// is deterministic, so a re-export over an up-to-date directory is a no-op
/// diff.
pub fn export_into(dir: &Path) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(dir)?;
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "ts") {
            fs::remove_file(&path)?;
        }
    }

    // The protocol roots; `export_all_to` pulls in every dependency
    // (envelope payloads, intents, and the domain-type mirrors).
    Query::export_all_to(dir)?;
    QueryEnvelope::<ApiError>::export_all_to(dir)?;
    MailListResult::export_all_to(dir)?;
    mirror::ThreadView::export_all_to(dir)?;
    MessageDetailResult::export_all_to(dir)?;
    MailboxCountsResult::export_all_to(dir)?;
    AccountsResult::export_all_to(dir)?;
    PendingOperationsResult::export_all_to(dir)?;
    CommandEnvelope::export_all_to(dir)?;
    CommandAccepted::export_all_to(dir)?;
    EventMessage::export_all_to(dir)?;
    ApiError::export_all_to(dir)?;

    write_barrel(dir)?;
    Ok(())
}

/// Writes `index.ts` re-exporting every generated module, sorted for a
/// stable diff.
fn write_barrel(dir: &Path) -> Result<(), Box<dyn Error>> {
    let mut modules: Vec<String> = fs::read_dir(dir)?
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension()? != "ts" {
                return None;
            }
            let stem = path.file_stem()?.to_str()?;
            (stem != "index").then(|| stem.to_string())
        })
        .collect();
    modules.sort();

    let mut barrel =
        String::from("// Generated by posthaste-client-models (just gen-ts). Do not hand-edit.\n");
    for module in modules {
        barrel.push_str(&format!("export * from \"./{module}\";\n"));
    }
    fs::write(dir.join("index.ts"), barrel)?;
    Ok(())
}
