[package]
name = "posthaste-lab"
version = "0.1.0"
edition = "2021"

[lib]
name = "posthaste_lab"
path = "src/lib.rs"

[[bin]]
name = "posthaste-lab"
path = "src/main.rs"

[dependencies]
posthaste-config = { path = "../posthaste-config" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }
