[package]
name = "posthaste-store"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { workspace = true }
posthaste-domain-model = { path = "../posthaste-domain-model" }
posthaste-domain-service = { path = "../posthaste-domain-service" }
posthaste-observability = { path = "../posthaste-observability" }
rusqlite = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
